[project]
name = 'Autonomous-Insurance-Pool'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.policy-contract]
path = 'contracts/policy-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.pool-management-contract]
path = 'contracts/pool-management-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.risk-assessment-contract]
path = 'contracts/risk-assessment-contract.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
